import mongoose, { Schema, ObjectId } from "mongoose";

const Sparse = mongoose.model(
  "Sparse",
  new Schema({
    id: { type: ObjectId },
    draw_date: { type: Date },
    num00: { type: Number, default: 0 },
    num01: { type: Number, default: 0 },
    num02: { type: Number, default: 0 },
    num03: { type: Number, default: 0 },
    num04: { type: Number, default: 0 },
    num05: { type: Number, default: 0 },
    num06: { type: Number, default: 0 },
    num07: { type: Number, default: 0 },
    num08: { type: Number, default: 0 },
    num09: { type: Number, default: 0 },
    num10: { type: Number, default: 0 },
    num11: { type: Number, default: 0 },
    num12: { type: Number, default: 0 },
    num13: { type: Number, default: 0 },
    num14: { type: Number, default: 0 },
    num15: { type: Number, default: 0 },
    num16: { type: Number, default: 0 },
    num17: { type: Number, default: 0 },
    num18: { type: Number, default: 0 },
    num19: { type: Number, default: 0 },
    num20: { type: Number, default: 0 },
    num21: { type: Number, default: 0 },
    num22: { type: Number, default: 0 },
    num23: { type: Number, default: 0 },
    num24: { type: Number, default: 0 },
    num25: { type: Number, default: 0 },
    num26: { type: Number, default: 0 },
    num27: { type: Number, default: 0 },
    num28: { type: Number, default: 0 },
    num29: { type: Number, default: 0 },
    num30: { type: Number, default: 0 },
    num31: { type: Number, default: 0 },
    num32: { type: Number, default: 0 },
    num33: { type: Number, default: 0 },
    num34: { type: Number, default: 0 },
    num35: { type: Number, default: 0 },
    num36: { type: Number, default: 0 },
    num37: { type: Number, default: 0 },
    num38: { type: Number, default: 0 },
    num39: { type: Number, default: 0 },
    num40: { type: Number, default: 0 },
    num41: { type: Number, default: 0 },
    num42: { type: Number, default: 0 },
    num43: { type: Number, default: 0 },
    num44: { type: Number, default: 0 },
    num45: { type: Number, default: 0 },
    num46: { type: Number, default: 0 },
    num47: { type: Number, default: 0 },
    num48: { type: Number, default: 0 },
    num49: { type: Number, default: 0 },
    num50: { type: Number, default: 0 },
    num51: { type: Number, default: 0 },
    num52: { type: Number, default: 0 },
    num53: { type: Number, default: 0 },
    num54: { type: Number, default: 0 },
    num55: { type: Number, default: 0 },
    num56: { type: Number, default: 0 },
    num57: { type: Number, default: 0 },
    num58: { type: Number, default: 0 },
    num59: { type: Number, default: 0 },
    num60: { type: Number, default: 0 },
    num61: { type: Number, default: 0 },
    num62: { type: Number, default: 0 },
    num63: { type: Number, default: 0 },
    num64: { type: Number, default: 0 },
    num65: { type: Number, default: 0 },
    num66: { type: Number, default: 0 },
    num67: { type: Number, default: 0 },
    num68: { type: Number, default: 0 },
    num69: { type: Number, default: 0 },
    num70: { type: Number, default: 0 },
    num71: { type: Number, default: 0 },
    num72: { type: Number, default: 0 },
    num73: { type: Number, default: 0 },
    num74: { type: Number, default: 0 },
    num75: { type: Number, default: 0 },
    num76: { type: Number, default: 0 },
    num77: { type: Number, default: 0 },
    num78: { type: Number, default: 0 },
    num79: { type: Number, default: 0 },
    num80: { type: Number, default: 0 },
    num81: { type: Number, default: 0 },
    num82: { type: Number, default: 0 },
    num83: { type: Number, default: 0 },
    num84: { type: Number, default: 0 },
    num85: { type: Number, default: 0 },
    num86: { type: Number, default: 0 },
    num87: { type: Number, default: 0 },
    num88: { type: Number, default: 0 },
    num89: { type: Number, default: 0 },
    num90: { type: Number, default: 0 },
    num91: { type: Number, default: 0 },
    num92: { type: Number, default: 0 },
    num93: { type: Number, default: 0 },
    num94: { type: Number, default: 0 },
    num95: { type: Number, default: 0 },
    num96: { type: Number, default: 0 },
    num97: { type: Number, default: 0 },
    num98: { type: Number, default: 0 },
    num99: { type: Number, default: 0 },
  })
);

export default Sparse;
